title: Gautier Evennou adad
description: PhD blog on computer vision and academic life.
baseurl: "/gautierevn"
url: "https://gautierevn.github.io"
name: PhD blog
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap