title: Gautier Evennou
description: PhD blog on computer vision and academic life.
baseurl: "/gautierevn"
url: "http://127.0.0.1:4000"
name: PhD blog
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap